---
# Playbook de gestion de SCREEN
- name: "Configuration SCREEN"
  hosts: all
  remote_user: bpr
  become: yes
  become_user: root
  become_method: sudo

  tasks:
    - name: "Install SCREEN package"
      apt:
        name: screen
        state: installed
