---
- hosts: new
  user: bpr
  sudo: yes

  tasks:
  - name: "sshd configuration file update"
    template:
      src: sshd_config.j2
      dest: /etc/ssh/sshd_config
      backup: yes
      owner: root
      group: root
      mode: 0644
      validate: '/usr/sbin/sshd -T -f %s'
    notify:
    - restart sshd

  handlers:
    - name: restart sshd
      service:
        name: sshd
        state: restarted
