---
# Playbook de gestion de dhclient.conf
- name: "DHCLIENT configuration"
  hosts: all
  remote_user: bpr
  sudo: yes

  tasks:
    - name: "DHCLIENT configuration"
      template:
        src=dhclient.j2
        dest=/etc/dhcp/dhclient.conf

    - name: "Change owner and group for dhclient.conf"
      file:
        path: /etc/dhcp/dhclient.conf
        owner: root
        group: root
        mode: 0644
