---
# Playbook initialisation Debian minimal
- name: "Debian initial setup"
  hosts: new
  remote_user: root
  
  vars_prompt:
    - name: "new_password"
      prompt: "Enter password for bpr user"
      private: yes
      encrypt: "md5_crypt"
      confirm: yes
      salt_size: 7

  tasks:
    - name: "Update apt and Upgrade packages"
      apt:
        update_cache: yes
        upgrade: dist

    - name: "Install sudo"
      apt:
        name: sudo
        state: present

    - name: "Create user bpr"
      user:
        name: bpr
        comment: "Bruno Prigent"
        shell: /bin/bash
        password: "{{new_password}}"
        groups: sudo

    - name: "Set authorized key"
      authorized_key:
        user: bpr
        state: present
        key: "{{ lookup('file', '/home/bpr/.ssh/authorized_keys') }}"

- include: ../role/all.yml

