---
# Playbook initialisation Ansible on Debian - additionnal packages
- name: "Debian initial setup - additionnal packages"
  hosts: all
  remote_user: bpr
  sudo: yes
  
  tasks:
    - name: "Update apt"
      apt:
        update_cache: yes

    - name: "Install package"
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - unzip
        - curl
