---
# Playbook initialisation Ansible on Debian domain server
# https://help.ubuntu.com/community/ActiveDirectoryWinbindHowto
- name: "Debian domain server initial setup"
  hosts: domain
  remote_user: bpr
  sudo: yes
  
  tasks:
    - name: "Update apt"
      apt:
        update_cache: yes

    - name: "Install package"
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - krb5-user
        - libpam-krb5
        - winbind
        - samba
        - cifs-utils
        - realmd

- include: ../app/dhclient/dhclient.yml

